/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthDashboardRouteImport } from './routes/auth/dashboard'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AccountPathRouteImport } from './routes/account/$path'
import { Route as AuthDashboardIndexRouteImport } from './routes/auth/dashboard/index'
import { Route as AuthDashboardSettingsRouteImport } from './routes/auth/dashboard/settings'
import { Route as AuthDashboardProfileRouteImport } from './routes/auth/dashboard/profile'
import { Route as AuthDashboardNotificationsRouteImport } from './routes/auth/dashboard/notifications'
import { Route as AuthDashboardKanabanRouteImport } from './routes/auth/dashboard/kanaban'
import { Route as AuthDashboardChatRouteImport } from './routes/auth/dashboard/chat'
import { Route as AuthDashboardAlertsRouteImport } from './routes/auth/dashboard/alerts'
import { Route as AuthDashboardAdminRouteImport } from './routes/auth/dashboard/admin'
import { Route as AuthDashboardActivityRouteImport } from './routes/auth/dashboard/activity'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthDashboardServicesIndexRouteImport } from './routes/auth/dashboard/services/index'
import { Route as AuthDashboardPatientsIndexRouteImport } from './routes/auth/dashboard/patients/index'
import { Route as AuthDashboardMedicalRecordsIndexRouteImport } from './routes/auth/dashboard/medical-records/index'
import { Route as AuthDashboardGrowthIndexRouteImport } from './routes/auth/dashboard/growth/index'
import { Route as AuthDashboardEncountersIndexRouteImport } from './routes/auth/dashboard/encounters/index'
import { Route as AuthDashboardDoctorsIndexRouteImport } from './routes/auth/dashboard/doctors/index'
import { Route as AuthDashboardAppointmentsIndexRouteImport } from './routes/auth/dashboard/appointments/index'
import { Route as AuthDashboardServicesNewRouteImport } from './routes/auth/dashboard/services/new'
import { Route as AuthDashboardServicesServiceIdRouteImport } from './routes/auth/dashboard/services/$serviceId'
import { Route as AuthDashboardPatientsNewRouteImport } from './routes/auth/dashboard/patients/new'
import { Route as AuthDashboardPatientsPatientIdRouteImport } from './routes/auth/dashboard/patients/$patientId'
import { Route as AuthDashboardMedicalRecordsNewRouteImport } from './routes/auth/dashboard/medical-records/new'
import { Route as AuthDashboardMedicalRecordsRecordIdRouteImport } from './routes/auth/dashboard/medical-records/$recordId'
import { Route as AuthDashboardGrowthRegisterRouteImport } from './routes/auth/dashboard/growth/register'
import { Route as AuthDashboardEncountersNewRouteImport } from './routes/auth/dashboard/encounters/new'
import { Route as AuthDashboardEncountersIdRouteImport } from './routes/auth/dashboard/encounters/$id'
import { Route as AuthDashboardDoctorsNewRouteImport } from './routes/auth/dashboard/doctors/new'
import { Route as AuthDashboardDoctorsDoctorIdRouteImport } from './routes/auth/dashboard/doctors/$doctorId'
import { Route as AuthDashboardAppointmentsTodayRouteImport } from './routes/auth/dashboard/appointments/today'
import { Route as AuthDashboardAppointmentsNewRouteImport } from './routes/auth/dashboard/appointments/new'
import { Route as AuthDashboardAppointmentsIdRouteImport } from './routes/auth/dashboard/appointments/$id'
import { Route as AuthDashboardGrowthPatientIdIndexRouteImport } from './routes/auth/dashboard/growth/$patientId/index'
import { Route as AuthDashboardServicesCloneServiceIdRouteImport } from './routes/auth/dashboard/services/clone/$serviceId'
import { Route as AuthDashboardServicesServiceIdEditRouteImport } from './routes/auth/dashboard/services/$serviceId.edit'
import { Route as AuthDashboardPatientsPatientIdEditRouteImport } from './routes/auth/dashboard/patients/$patientId/edit'
import { Route as AuthDashboardMedicalRecordsRecordIdEditRouteImport } from './routes/auth/dashboard/medical-records/$recordId.edit'
import { Route as AuthDashboardGrowthPatientIdChartRouteImport } from './routes/auth/dashboard/growth/$patientId/chart'
import { Route as AuthDashboardGrowthPatientIdAddMeasurementRouteImport } from './routes/auth/dashboard/growth/$patientId/add-measurement'
import { Route as AuthDashboardEncountersIdEditRouteImport } from './routes/auth/dashboard/encounters/$id.edit'
import { Route as AuthDashboardAppointmentsIdRescheduleRouteImport } from './routes/auth/dashboard/appointments/$id.reschedule'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AccountPathRoute = AccountPathRouteImport.update({
  id: '/account/$path',
  path: '/account/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardProfileRoute = AuthDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardNotificationsRoute =
  AuthDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardKanabanRoute = AuthDashboardKanabanRouteImport.update({
  id: '/kanaban',
  path: '/kanaban',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardChatRoute = AuthDashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardAlertsRoute = AuthDashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardAdminRoute = AuthDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardActivityRoute = AuthDashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardServicesIndexRoute =
  AuthDashboardServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardPatientsIndexRoute =
  AuthDashboardPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardMedicalRecordsIndexRoute =
  AuthDashboardMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardGrowthIndexRoute =
  AuthDashboardGrowthIndexRouteImport.update({
    id: '/growth/',
    path: '/growth/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEncountersIndexRoute =
  AuthDashboardEncountersIndexRouteImport.update({
    id: '/encounters/',
    path: '/encounters/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardDoctorsIndexRoute =
  AuthDashboardDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAppointmentsIndexRoute =
  AuthDashboardAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardServicesNewRoute =
  AuthDashboardServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardServicesServiceIdRoute =
  AuthDashboardServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardPatientsNewRoute =
  AuthDashboardPatientsNewRouteImport.update({
    id: '/patients/new',
    path: '/patients/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardPatientsPatientIdRoute =
  AuthDashboardPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardMedicalRecordsNewRoute =
  AuthDashboardMedicalRecordsNewRouteImport.update({
    id: '/medical-records/new',
    path: '/medical-records/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardMedicalRecordsRecordIdRoute =
  AuthDashboardMedicalRecordsRecordIdRouteImport.update({
    id: '/medical-records/$recordId',
    path: '/medical-records/$recordId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardGrowthRegisterRoute =
  AuthDashboardGrowthRegisterRouteImport.update({
    id: '/growth/register',
    path: '/growth/register',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEncountersNewRoute =
  AuthDashboardEncountersNewRouteImport.update({
    id: '/encounters/new',
    path: '/encounters/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEncountersIdRoute =
  AuthDashboardEncountersIdRouteImport.update({
    id: '/encounters/$id',
    path: '/encounters/$id',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardDoctorsNewRoute = AuthDashboardDoctorsNewRouteImport.update({
  id: '/doctors/new',
  path: '/doctors/new',
  getParentRoute: () => AuthDashboardRoute,
} as any)
const AuthDashboardDoctorsDoctorIdRoute =
  AuthDashboardDoctorsDoctorIdRouteImport.update({
    id: '/doctors/$doctorId',
    path: '/doctors/$doctorId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAppointmentsTodayRoute =
  AuthDashboardAppointmentsTodayRouteImport.update({
    id: '/appointments/today',
    path: '/appointments/today',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAppointmentsNewRoute =
  AuthDashboardAppointmentsNewRouteImport.update({
    id: '/appointments/new',
    path: '/appointments/new',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardAppointmentsIdRoute =
  AuthDashboardAppointmentsIdRouteImport.update({
    id: '/appointments/$id',
    path: '/appointments/$id',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardGrowthPatientIdIndexRoute =
  AuthDashboardGrowthPatientIdIndexRouteImport.update({
    id: '/growth/$patientId/',
    path: '/growth/$patientId/',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardServicesCloneServiceIdRoute =
  AuthDashboardServicesCloneServiceIdRouteImport.update({
    id: '/services/clone/$serviceId',
    path: '/services/clone/$serviceId',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardServicesServiceIdEditRoute =
  AuthDashboardServicesServiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardServicesServiceIdRoute,
  } as any)
const AuthDashboardPatientsPatientIdEditRoute =
  AuthDashboardPatientsPatientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardPatientsPatientIdRoute,
  } as any)
const AuthDashboardMedicalRecordsRecordIdEditRoute =
  AuthDashboardMedicalRecordsRecordIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardMedicalRecordsRecordIdRoute,
  } as any)
const AuthDashboardGrowthPatientIdChartRoute =
  AuthDashboardGrowthPatientIdChartRouteImport.update({
    id: '/growth/$patientId/chart',
    path: '/growth/$patientId/chart',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardGrowthPatientIdAddMeasurementRoute =
  AuthDashboardGrowthPatientIdAddMeasurementRouteImport.update({
    id: '/growth/$patientId/add-measurement',
    path: '/growth/$patientId/add-measurement',
    getParentRoute: () => AuthDashboardRoute,
  } as any)
const AuthDashboardEncountersIdEditRoute =
  AuthDashboardEncountersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthDashboardEncountersIdRoute,
  } as any)
const AuthDashboardAppointmentsIdRescheduleRoute =
  AuthDashboardAppointmentsIdRescheduleRouteImport.update({
    id: '/reschedule',
    path: '/reschedule',
    getParentRoute: () => AuthDashboardAppointmentsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/account/$path': typeof AccountPathRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/dashboard/activity': typeof AuthDashboardActivityRoute
  '/auth/dashboard/admin': typeof AuthDashboardAdminRoute
  '/auth/dashboard/alerts': typeof AuthDashboardAlertsRoute
  '/auth/dashboard/chat': typeof AuthDashboardChatRoute
  '/auth/dashboard/kanaban': typeof AuthDashboardKanabanRoute
  '/auth/dashboard/notifications': typeof AuthDashboardNotificationsRoute
  '/auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/auth/dashboard/': typeof AuthDashboardIndexRoute
  '/auth/dashboard/appointments/$id': typeof AuthDashboardAppointmentsIdRouteWithChildren
  '/auth/dashboard/appointments/new': typeof AuthDashboardAppointmentsNewRoute
  '/auth/dashboard/appointments/today': typeof AuthDashboardAppointmentsTodayRoute
  '/auth/dashboard/doctors/$doctorId': typeof AuthDashboardDoctorsDoctorIdRoute
  '/auth/dashboard/doctors/new': typeof AuthDashboardDoctorsNewRoute
  '/auth/dashboard/encounters/$id': typeof AuthDashboardEncountersIdRouteWithChildren
  '/auth/dashboard/encounters/new': typeof AuthDashboardEncountersNewRoute
  '/auth/dashboard/growth/register': typeof AuthDashboardGrowthRegisterRoute
  '/auth/dashboard/medical-records/$recordId': typeof AuthDashboardMedicalRecordsRecordIdRouteWithChildren
  '/auth/dashboard/medical-records/new': typeof AuthDashboardMedicalRecordsNewRoute
  '/auth/dashboard/patients/$patientId': typeof AuthDashboardPatientsPatientIdRouteWithChildren
  '/auth/dashboard/patients/new': typeof AuthDashboardPatientsNewRoute
  '/auth/dashboard/services/$serviceId': typeof AuthDashboardServicesServiceIdRouteWithChildren
  '/auth/dashboard/services/new': typeof AuthDashboardServicesNewRoute
  '/auth/dashboard/appointments/': typeof AuthDashboardAppointmentsIndexRoute
  '/auth/dashboard/doctors/': typeof AuthDashboardDoctorsIndexRoute
  '/auth/dashboard/encounters/': typeof AuthDashboardEncountersIndexRoute
  '/auth/dashboard/growth/': typeof AuthDashboardGrowthIndexRoute
  '/auth/dashboard/medical-records/': typeof AuthDashboardMedicalRecordsIndexRoute
  '/auth/dashboard/patients/': typeof AuthDashboardPatientsIndexRoute
  '/auth/dashboard/services/': typeof AuthDashboardServicesIndexRoute
  '/auth/dashboard/appointments/$id/reschedule': typeof AuthDashboardAppointmentsIdRescheduleRoute
  '/auth/dashboard/encounters/$id/edit': typeof AuthDashboardEncountersIdEditRoute
  '/auth/dashboard/growth/$patientId/add-measurement': typeof AuthDashboardGrowthPatientIdAddMeasurementRoute
  '/auth/dashboard/growth/$patientId/chart': typeof AuthDashboardGrowthPatientIdChartRoute
  '/auth/dashboard/medical-records/$recordId/edit': typeof AuthDashboardMedicalRecordsRecordIdEditRoute
  '/auth/dashboard/patients/$patientId/edit': typeof AuthDashboardPatientsPatientIdEditRoute
  '/auth/dashboard/services/$serviceId/edit': typeof AuthDashboardServicesServiceIdEditRoute
  '/auth/dashboard/services/clone/$serviceId': typeof AuthDashboardServicesCloneServiceIdRoute
  '/auth/dashboard/growth/$patientId/': typeof AuthDashboardGrowthPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/account/$path': typeof AccountPathRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/dashboard/activity': typeof AuthDashboardActivityRoute
  '/auth/dashboard/admin': typeof AuthDashboardAdminRoute
  '/auth/dashboard/alerts': typeof AuthDashboardAlertsRoute
  '/auth/dashboard/chat': typeof AuthDashboardChatRoute
  '/auth/dashboard/kanaban': typeof AuthDashboardKanabanRoute
  '/auth/dashboard/notifications': typeof AuthDashboardNotificationsRoute
  '/auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/auth/dashboard': typeof AuthDashboardIndexRoute
  '/auth/dashboard/appointments/$id': typeof AuthDashboardAppointmentsIdRouteWithChildren
  '/auth/dashboard/appointments/new': typeof AuthDashboardAppointmentsNewRoute
  '/auth/dashboard/appointments/today': typeof AuthDashboardAppointmentsTodayRoute
  '/auth/dashboard/doctors/$doctorId': typeof AuthDashboardDoctorsDoctorIdRoute
  '/auth/dashboard/doctors/new': typeof AuthDashboardDoctorsNewRoute
  '/auth/dashboard/encounters/$id': typeof AuthDashboardEncountersIdRouteWithChildren
  '/auth/dashboard/encounters/new': typeof AuthDashboardEncountersNewRoute
  '/auth/dashboard/growth/register': typeof AuthDashboardGrowthRegisterRoute
  '/auth/dashboard/medical-records/$recordId': typeof AuthDashboardMedicalRecordsRecordIdRouteWithChildren
  '/auth/dashboard/medical-records/new': typeof AuthDashboardMedicalRecordsNewRoute
  '/auth/dashboard/patients/$patientId': typeof AuthDashboardPatientsPatientIdRouteWithChildren
  '/auth/dashboard/patients/new': typeof AuthDashboardPatientsNewRoute
  '/auth/dashboard/services/$serviceId': typeof AuthDashboardServicesServiceIdRouteWithChildren
  '/auth/dashboard/services/new': typeof AuthDashboardServicesNewRoute
  '/auth/dashboard/appointments': typeof AuthDashboardAppointmentsIndexRoute
  '/auth/dashboard/doctors': typeof AuthDashboardDoctorsIndexRoute
  '/auth/dashboard/encounters': typeof AuthDashboardEncountersIndexRoute
  '/auth/dashboard/growth': typeof AuthDashboardGrowthIndexRoute
  '/auth/dashboard/medical-records': typeof AuthDashboardMedicalRecordsIndexRoute
  '/auth/dashboard/patients': typeof AuthDashboardPatientsIndexRoute
  '/auth/dashboard/services': typeof AuthDashboardServicesIndexRoute
  '/auth/dashboard/appointments/$id/reschedule': typeof AuthDashboardAppointmentsIdRescheduleRoute
  '/auth/dashboard/encounters/$id/edit': typeof AuthDashboardEncountersIdEditRoute
  '/auth/dashboard/growth/$patientId/add-measurement': typeof AuthDashboardGrowthPatientIdAddMeasurementRoute
  '/auth/dashboard/growth/$patientId/chart': typeof AuthDashboardGrowthPatientIdChartRoute
  '/auth/dashboard/medical-records/$recordId/edit': typeof AuthDashboardMedicalRecordsRecordIdEditRoute
  '/auth/dashboard/patients/$patientId/edit': typeof AuthDashboardPatientsPatientIdEditRoute
  '/auth/dashboard/services/$serviceId/edit': typeof AuthDashboardServicesServiceIdEditRoute
  '/auth/dashboard/services/clone/$serviceId': typeof AuthDashboardServicesCloneServiceIdRoute
  '/auth/dashboard/growth/$patientId': typeof AuthDashboardGrowthPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/account/$path': typeof AccountPathRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/dashboard': typeof AuthDashboardRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/dashboard/activity': typeof AuthDashboardActivityRoute
  '/auth/dashboard/admin': typeof AuthDashboardAdminRoute
  '/auth/dashboard/alerts': typeof AuthDashboardAlertsRoute
  '/auth/dashboard/chat': typeof AuthDashboardChatRoute
  '/auth/dashboard/kanaban': typeof AuthDashboardKanabanRoute
  '/auth/dashboard/notifications': typeof AuthDashboardNotificationsRoute
  '/auth/dashboard/profile': typeof AuthDashboardProfileRoute
  '/auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/auth/dashboard/': typeof AuthDashboardIndexRoute
  '/auth/dashboard/appointments/$id': typeof AuthDashboardAppointmentsIdRouteWithChildren
  '/auth/dashboard/appointments/new': typeof AuthDashboardAppointmentsNewRoute
  '/auth/dashboard/appointments/today': typeof AuthDashboardAppointmentsTodayRoute
  '/auth/dashboard/doctors/$doctorId': typeof AuthDashboardDoctorsDoctorIdRoute
  '/auth/dashboard/doctors/new': typeof AuthDashboardDoctorsNewRoute
  '/auth/dashboard/encounters/$id': typeof AuthDashboardEncountersIdRouteWithChildren
  '/auth/dashboard/encounters/new': typeof AuthDashboardEncountersNewRoute
  '/auth/dashboard/growth/register': typeof AuthDashboardGrowthRegisterRoute
  '/auth/dashboard/medical-records/$recordId': typeof AuthDashboardMedicalRecordsRecordIdRouteWithChildren
  '/auth/dashboard/medical-records/new': typeof AuthDashboardMedicalRecordsNewRoute
  '/auth/dashboard/patients/$patientId': typeof AuthDashboardPatientsPatientIdRouteWithChildren
  '/auth/dashboard/patients/new': typeof AuthDashboardPatientsNewRoute
  '/auth/dashboard/services/$serviceId': typeof AuthDashboardServicesServiceIdRouteWithChildren
  '/auth/dashboard/services/new': typeof AuthDashboardServicesNewRoute
  '/auth/dashboard/appointments/': typeof AuthDashboardAppointmentsIndexRoute
  '/auth/dashboard/doctors/': typeof AuthDashboardDoctorsIndexRoute
  '/auth/dashboard/encounters/': typeof AuthDashboardEncountersIndexRoute
  '/auth/dashboard/growth/': typeof AuthDashboardGrowthIndexRoute
  '/auth/dashboard/medical-records/': typeof AuthDashboardMedicalRecordsIndexRoute
  '/auth/dashboard/patients/': typeof AuthDashboardPatientsIndexRoute
  '/auth/dashboard/services/': typeof AuthDashboardServicesIndexRoute
  '/auth/dashboard/appointments/$id/reschedule': typeof AuthDashboardAppointmentsIdRescheduleRoute
  '/auth/dashboard/encounters/$id/edit': typeof AuthDashboardEncountersIdEditRoute
  '/auth/dashboard/growth/$patientId/add-measurement': typeof AuthDashboardGrowthPatientIdAddMeasurementRoute
  '/auth/dashboard/growth/$patientId/chart': typeof AuthDashboardGrowthPatientIdChartRoute
  '/auth/dashboard/medical-records/$recordId/edit': typeof AuthDashboardMedicalRecordsRecordIdEditRoute
  '/auth/dashboard/patients/$patientId/edit': typeof AuthDashboardPatientsPatientIdEditRoute
  '/auth/dashboard/services/$serviceId/edit': typeof AuthDashboardServicesServiceIdEditRoute
  '/auth/dashboard/services/clone/$serviceId': typeof AuthDashboardServicesCloneServiceIdRoute
  '/auth/dashboard/growth/$patientId/': typeof AuthDashboardGrowthPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/contact'
    | '/services'
    | '/testimonials'
    | '/account/$path'
    | '/auth/$path'
    | '/auth/dashboard'
    | '/auth/forgot-password'
    | '/api/auth/$'
    | '/auth/dashboard/activity'
    | '/auth/dashboard/admin'
    | '/auth/dashboard/alerts'
    | '/auth/dashboard/chat'
    | '/auth/dashboard/kanaban'
    | '/auth/dashboard/notifications'
    | '/auth/dashboard/profile'
    | '/auth/dashboard/settings'
    | '/auth/dashboard/'
    | '/auth/dashboard/appointments/$id'
    | '/auth/dashboard/appointments/new'
    | '/auth/dashboard/appointments/today'
    | '/auth/dashboard/doctors/$doctorId'
    | '/auth/dashboard/doctors/new'
    | '/auth/dashboard/encounters/$id'
    | '/auth/dashboard/encounters/new'
    | '/auth/dashboard/growth/register'
    | '/auth/dashboard/medical-records/$recordId'
    | '/auth/dashboard/medical-records/new'
    | '/auth/dashboard/patients/$patientId'
    | '/auth/dashboard/patients/new'
    | '/auth/dashboard/services/$serviceId'
    | '/auth/dashboard/services/new'
    | '/auth/dashboard/appointments/'
    | '/auth/dashboard/doctors/'
    | '/auth/dashboard/encounters/'
    | '/auth/dashboard/growth/'
    | '/auth/dashboard/medical-records/'
    | '/auth/dashboard/patients/'
    | '/auth/dashboard/services/'
    | '/auth/dashboard/appointments/$id/reschedule'
    | '/auth/dashboard/encounters/$id/edit'
    | '/auth/dashboard/growth/$patientId/add-measurement'
    | '/auth/dashboard/growth/$patientId/chart'
    | '/auth/dashboard/medical-records/$recordId/edit'
    | '/auth/dashboard/patients/$patientId/edit'
    | '/auth/dashboard/services/$serviceId/edit'
    | '/auth/dashboard/services/clone/$serviceId'
    | '/auth/dashboard/growth/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/about'
    | '/contact'
    | '/services'
    | '/testimonials'
    | '/account/$path'
    | '/auth/$path'
    | '/auth/forgot-password'
    | '/api/auth/$'
    | '/auth/dashboard/activity'
    | '/auth/dashboard/admin'
    | '/auth/dashboard/alerts'
    | '/auth/dashboard/chat'
    | '/auth/dashboard/kanaban'
    | '/auth/dashboard/notifications'
    | '/auth/dashboard/profile'
    | '/auth/dashboard/settings'
    | '/auth/dashboard'
    | '/auth/dashboard/appointments/$id'
    | '/auth/dashboard/appointments/new'
    | '/auth/dashboard/appointments/today'
    | '/auth/dashboard/doctors/$doctorId'
    | '/auth/dashboard/doctors/new'
    | '/auth/dashboard/encounters/$id'
    | '/auth/dashboard/encounters/new'
    | '/auth/dashboard/growth/register'
    | '/auth/dashboard/medical-records/$recordId'
    | '/auth/dashboard/medical-records/new'
    | '/auth/dashboard/patients/$patientId'
    | '/auth/dashboard/patients/new'
    | '/auth/dashboard/services/$serviceId'
    | '/auth/dashboard/services/new'
    | '/auth/dashboard/appointments'
    | '/auth/dashboard/doctors'
    | '/auth/dashboard/encounters'
    | '/auth/dashboard/growth'
    | '/auth/dashboard/medical-records'
    | '/auth/dashboard/patients'
    | '/auth/dashboard/services'
    | '/auth/dashboard/appointments/$id/reschedule'
    | '/auth/dashboard/encounters/$id/edit'
    | '/auth/dashboard/growth/$patientId/add-measurement'
    | '/auth/dashboard/growth/$patientId/chart'
    | '/auth/dashboard/medical-records/$recordId/edit'
    | '/auth/dashboard/patients/$patientId/edit'
    | '/auth/dashboard/services/$serviceId/edit'
    | '/auth/dashboard/services/clone/$serviceId'
    | '/auth/dashboard/growth/$patientId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/about'
    | '/contact'
    | '/services'
    | '/testimonials'
    | '/account/$path'
    | '/auth/$path'
    | '/auth/dashboard'
    | '/auth/forgot-password'
    | '/api/auth/$'
    | '/auth/dashboard/activity'
    | '/auth/dashboard/admin'
    | '/auth/dashboard/alerts'
    | '/auth/dashboard/chat'
    | '/auth/dashboard/kanaban'
    | '/auth/dashboard/notifications'
    | '/auth/dashboard/profile'
    | '/auth/dashboard/settings'
    | '/auth/dashboard/'
    | '/auth/dashboard/appointments/$id'
    | '/auth/dashboard/appointments/new'
    | '/auth/dashboard/appointments/today'
    | '/auth/dashboard/doctors/$doctorId'
    | '/auth/dashboard/doctors/new'
    | '/auth/dashboard/encounters/$id'
    | '/auth/dashboard/encounters/new'
    | '/auth/dashboard/growth/register'
    | '/auth/dashboard/medical-records/$recordId'
    | '/auth/dashboard/medical-records/new'
    | '/auth/dashboard/patients/$patientId'
    | '/auth/dashboard/patients/new'
    | '/auth/dashboard/services/$serviceId'
    | '/auth/dashboard/services/new'
    | '/auth/dashboard/appointments/'
    | '/auth/dashboard/doctors/'
    | '/auth/dashboard/encounters/'
    | '/auth/dashboard/growth/'
    | '/auth/dashboard/medical-records/'
    | '/auth/dashboard/patients/'
    | '/auth/dashboard/services/'
    | '/auth/dashboard/appointments/$id/reschedule'
    | '/auth/dashboard/encounters/$id/edit'
    | '/auth/dashboard/growth/$patientId/add-measurement'
    | '/auth/dashboard/growth/$patientId/chart'
    | '/auth/dashboard/medical-records/$recordId/edit'
    | '/auth/dashboard/patients/$patientId/edit'
    | '/auth/dashboard/services/$serviceId/edit'
    | '/auth/dashboard/services/clone/$serviceId'
    | '/auth/dashboard/growth/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  AccountPathRoute: typeof AccountPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/dashboard': {
      id: '/auth/dashboard'
      path: '/dashboard'
      fullPath: '/auth/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/account/$path': {
      id: '/account/$path'
      path: '/account/$path'
      fullPath: '/account/$path'
      preLoaderRoute: typeof AccountPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dashboard/': {
      id: '/auth/dashboard/'
      path: '/'
      fullPath: '/auth/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/settings': {
      id: '/auth/dashboard/settings'
      path: '/settings'
      fullPath: '/auth/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/profile': {
      id: '/auth/dashboard/profile'
      path: '/profile'
      fullPath: '/auth/dashboard/profile'
      preLoaderRoute: typeof AuthDashboardProfileRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/notifications': {
      id: '/auth/dashboard/notifications'
      path: '/notifications'
      fullPath: '/auth/dashboard/notifications'
      preLoaderRoute: typeof AuthDashboardNotificationsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/kanaban': {
      id: '/auth/dashboard/kanaban'
      path: '/kanaban'
      fullPath: '/auth/dashboard/kanaban'
      preLoaderRoute: typeof AuthDashboardKanabanRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/chat': {
      id: '/auth/dashboard/chat'
      path: '/chat'
      fullPath: '/auth/dashboard/chat'
      preLoaderRoute: typeof AuthDashboardChatRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/alerts': {
      id: '/auth/dashboard/alerts'
      path: '/alerts'
      fullPath: '/auth/dashboard/alerts'
      preLoaderRoute: typeof AuthDashboardAlertsRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/admin': {
      id: '/auth/dashboard/admin'
      path: '/admin'
      fullPath: '/auth/dashboard/admin'
      preLoaderRoute: typeof AuthDashboardAdminRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/activity': {
      id: '/auth/dashboard/activity'
      path: '/activity'
      fullPath: '/auth/dashboard/activity'
      preLoaderRoute: typeof AuthDashboardActivityRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/dashboard/services/': {
      id: '/auth/dashboard/services/'
      path: '/services'
      fullPath: '/auth/dashboard/services/'
      preLoaderRoute: typeof AuthDashboardServicesIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/patients/': {
      id: '/auth/dashboard/patients/'
      path: '/patients'
      fullPath: '/auth/dashboard/patients/'
      preLoaderRoute: typeof AuthDashboardPatientsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/medical-records/': {
      id: '/auth/dashboard/medical-records/'
      path: '/medical-records'
      fullPath: '/auth/dashboard/medical-records/'
      preLoaderRoute: typeof AuthDashboardMedicalRecordsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/growth/': {
      id: '/auth/dashboard/growth/'
      path: '/growth'
      fullPath: '/auth/dashboard/growth/'
      preLoaderRoute: typeof AuthDashboardGrowthIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/encounters/': {
      id: '/auth/dashboard/encounters/'
      path: '/encounters'
      fullPath: '/auth/dashboard/encounters/'
      preLoaderRoute: typeof AuthDashboardEncountersIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/doctors/': {
      id: '/auth/dashboard/doctors/'
      path: '/doctors'
      fullPath: '/auth/dashboard/doctors/'
      preLoaderRoute: typeof AuthDashboardDoctorsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/appointments/': {
      id: '/auth/dashboard/appointments/'
      path: '/appointments'
      fullPath: '/auth/dashboard/appointments/'
      preLoaderRoute: typeof AuthDashboardAppointmentsIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/services/new': {
      id: '/auth/dashboard/services/new'
      path: '/services/new'
      fullPath: '/auth/dashboard/services/new'
      preLoaderRoute: typeof AuthDashboardServicesNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/services/$serviceId': {
      id: '/auth/dashboard/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/auth/dashboard/services/$serviceId'
      preLoaderRoute: typeof AuthDashboardServicesServiceIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/patients/new': {
      id: '/auth/dashboard/patients/new'
      path: '/patients/new'
      fullPath: '/auth/dashboard/patients/new'
      preLoaderRoute: typeof AuthDashboardPatientsNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/patients/$patientId': {
      id: '/auth/dashboard/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/auth/dashboard/patients/$patientId'
      preLoaderRoute: typeof AuthDashboardPatientsPatientIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/medical-records/new': {
      id: '/auth/dashboard/medical-records/new'
      path: '/medical-records/new'
      fullPath: '/auth/dashboard/medical-records/new'
      preLoaderRoute: typeof AuthDashboardMedicalRecordsNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/medical-records/$recordId': {
      id: '/auth/dashboard/medical-records/$recordId'
      path: '/medical-records/$recordId'
      fullPath: '/auth/dashboard/medical-records/$recordId'
      preLoaderRoute: typeof AuthDashboardMedicalRecordsRecordIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/growth/register': {
      id: '/auth/dashboard/growth/register'
      path: '/growth/register'
      fullPath: '/auth/dashboard/growth/register'
      preLoaderRoute: typeof AuthDashboardGrowthRegisterRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/encounters/new': {
      id: '/auth/dashboard/encounters/new'
      path: '/encounters/new'
      fullPath: '/auth/dashboard/encounters/new'
      preLoaderRoute: typeof AuthDashboardEncountersNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/encounters/$id': {
      id: '/auth/dashboard/encounters/$id'
      path: '/encounters/$id'
      fullPath: '/auth/dashboard/encounters/$id'
      preLoaderRoute: typeof AuthDashboardEncountersIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/doctors/new': {
      id: '/auth/dashboard/doctors/new'
      path: '/doctors/new'
      fullPath: '/auth/dashboard/doctors/new'
      preLoaderRoute: typeof AuthDashboardDoctorsNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/doctors/$doctorId': {
      id: '/auth/dashboard/doctors/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/auth/dashboard/doctors/$doctorId'
      preLoaderRoute: typeof AuthDashboardDoctorsDoctorIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/appointments/today': {
      id: '/auth/dashboard/appointments/today'
      path: '/appointments/today'
      fullPath: '/auth/dashboard/appointments/today'
      preLoaderRoute: typeof AuthDashboardAppointmentsTodayRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/appointments/new': {
      id: '/auth/dashboard/appointments/new'
      path: '/appointments/new'
      fullPath: '/auth/dashboard/appointments/new'
      preLoaderRoute: typeof AuthDashboardAppointmentsNewRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/appointments/$id': {
      id: '/auth/dashboard/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/auth/dashboard/appointments/$id'
      preLoaderRoute: typeof AuthDashboardAppointmentsIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/growth/$patientId/': {
      id: '/auth/dashboard/growth/$patientId/'
      path: '/growth/$patientId'
      fullPath: '/auth/dashboard/growth/$patientId/'
      preLoaderRoute: typeof AuthDashboardGrowthPatientIdIndexRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/services/clone/$serviceId': {
      id: '/auth/dashboard/services/clone/$serviceId'
      path: '/services/clone/$serviceId'
      fullPath: '/auth/dashboard/services/clone/$serviceId'
      preLoaderRoute: typeof AuthDashboardServicesCloneServiceIdRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/services/$serviceId/edit': {
      id: '/auth/dashboard/services/$serviceId/edit'
      path: '/edit'
      fullPath: '/auth/dashboard/services/$serviceId/edit'
      preLoaderRoute: typeof AuthDashboardServicesServiceIdEditRouteImport
      parentRoute: typeof AuthDashboardServicesServiceIdRoute
    }
    '/auth/dashboard/patients/$patientId/edit': {
      id: '/auth/dashboard/patients/$patientId/edit'
      path: '/edit'
      fullPath: '/auth/dashboard/patients/$patientId/edit'
      preLoaderRoute: typeof AuthDashboardPatientsPatientIdEditRouteImport
      parentRoute: typeof AuthDashboardPatientsPatientIdRoute
    }
    '/auth/dashboard/medical-records/$recordId/edit': {
      id: '/auth/dashboard/medical-records/$recordId/edit'
      path: '/edit'
      fullPath: '/auth/dashboard/medical-records/$recordId/edit'
      preLoaderRoute: typeof AuthDashboardMedicalRecordsRecordIdEditRouteImport
      parentRoute: typeof AuthDashboardMedicalRecordsRecordIdRoute
    }
    '/auth/dashboard/growth/$patientId/chart': {
      id: '/auth/dashboard/growth/$patientId/chart'
      path: '/growth/$patientId/chart'
      fullPath: '/auth/dashboard/growth/$patientId/chart'
      preLoaderRoute: typeof AuthDashboardGrowthPatientIdChartRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/growth/$patientId/add-measurement': {
      id: '/auth/dashboard/growth/$patientId/add-measurement'
      path: '/growth/$patientId/add-measurement'
      fullPath: '/auth/dashboard/growth/$patientId/add-measurement'
      preLoaderRoute: typeof AuthDashboardGrowthPatientIdAddMeasurementRouteImport
      parentRoute: typeof AuthDashboardRoute
    }
    '/auth/dashboard/encounters/$id/edit': {
      id: '/auth/dashboard/encounters/$id/edit'
      path: '/edit'
      fullPath: '/auth/dashboard/encounters/$id/edit'
      preLoaderRoute: typeof AuthDashboardEncountersIdEditRouteImport
      parentRoute: typeof AuthDashboardEncountersIdRoute
    }
    '/auth/dashboard/appointments/$id/reschedule': {
      id: '/auth/dashboard/appointments/$id/reschedule'
      path: '/reschedule'
      fullPath: '/auth/dashboard/appointments/$id/reschedule'
      preLoaderRoute: typeof AuthDashboardAppointmentsIdRescheduleRouteImport
      parentRoute: typeof AuthDashboardAppointmentsIdRoute
    }
  }
}

interface AuthDashboardAppointmentsIdRouteChildren {
  AuthDashboardAppointmentsIdRescheduleRoute: typeof AuthDashboardAppointmentsIdRescheduleRoute
}

const AuthDashboardAppointmentsIdRouteChildren: AuthDashboardAppointmentsIdRouteChildren =
  {
    AuthDashboardAppointmentsIdRescheduleRoute:
      AuthDashboardAppointmentsIdRescheduleRoute,
  }

const AuthDashboardAppointmentsIdRouteWithChildren =
  AuthDashboardAppointmentsIdRoute._addFileChildren(
    AuthDashboardAppointmentsIdRouteChildren,
  )

interface AuthDashboardEncountersIdRouteChildren {
  AuthDashboardEncountersIdEditRoute: typeof AuthDashboardEncountersIdEditRoute
}

const AuthDashboardEncountersIdRouteChildren: AuthDashboardEncountersIdRouteChildren =
  {
    AuthDashboardEncountersIdEditRoute: AuthDashboardEncountersIdEditRoute,
  }

const AuthDashboardEncountersIdRouteWithChildren =
  AuthDashboardEncountersIdRoute._addFileChildren(
    AuthDashboardEncountersIdRouteChildren,
  )

interface AuthDashboardMedicalRecordsRecordIdRouteChildren {
  AuthDashboardMedicalRecordsRecordIdEditRoute: typeof AuthDashboardMedicalRecordsRecordIdEditRoute
}

const AuthDashboardMedicalRecordsRecordIdRouteChildren: AuthDashboardMedicalRecordsRecordIdRouteChildren =
  {
    AuthDashboardMedicalRecordsRecordIdEditRoute:
      AuthDashboardMedicalRecordsRecordIdEditRoute,
  }

const AuthDashboardMedicalRecordsRecordIdRouteWithChildren =
  AuthDashboardMedicalRecordsRecordIdRoute._addFileChildren(
    AuthDashboardMedicalRecordsRecordIdRouteChildren,
  )

interface AuthDashboardPatientsPatientIdRouteChildren {
  AuthDashboardPatientsPatientIdEditRoute: typeof AuthDashboardPatientsPatientIdEditRoute
}

const AuthDashboardPatientsPatientIdRouteChildren: AuthDashboardPatientsPatientIdRouteChildren =
  {
    AuthDashboardPatientsPatientIdEditRoute:
      AuthDashboardPatientsPatientIdEditRoute,
  }

const AuthDashboardPatientsPatientIdRouteWithChildren =
  AuthDashboardPatientsPatientIdRoute._addFileChildren(
    AuthDashboardPatientsPatientIdRouteChildren,
  )

interface AuthDashboardServicesServiceIdRouteChildren {
  AuthDashboardServicesServiceIdEditRoute: typeof AuthDashboardServicesServiceIdEditRoute
}

const AuthDashboardServicesServiceIdRouteChildren: AuthDashboardServicesServiceIdRouteChildren =
  {
    AuthDashboardServicesServiceIdEditRoute:
      AuthDashboardServicesServiceIdEditRoute,
  }

const AuthDashboardServicesServiceIdRouteWithChildren =
  AuthDashboardServicesServiceIdRoute._addFileChildren(
    AuthDashboardServicesServiceIdRouteChildren,
  )

interface AuthDashboardRouteChildren {
  AuthDashboardActivityRoute: typeof AuthDashboardActivityRoute
  AuthDashboardAdminRoute: typeof AuthDashboardAdminRoute
  AuthDashboardAlertsRoute: typeof AuthDashboardAlertsRoute
  AuthDashboardChatRoute: typeof AuthDashboardChatRoute
  AuthDashboardKanabanRoute: typeof AuthDashboardKanabanRoute
  AuthDashboardNotificationsRoute: typeof AuthDashboardNotificationsRoute
  AuthDashboardProfileRoute: typeof AuthDashboardProfileRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardAppointmentsIdRoute: typeof AuthDashboardAppointmentsIdRouteWithChildren
  AuthDashboardAppointmentsNewRoute: typeof AuthDashboardAppointmentsNewRoute
  AuthDashboardAppointmentsTodayRoute: typeof AuthDashboardAppointmentsTodayRoute
  AuthDashboardDoctorsDoctorIdRoute: typeof AuthDashboardDoctorsDoctorIdRoute
  AuthDashboardDoctorsNewRoute: typeof AuthDashboardDoctorsNewRoute
  AuthDashboardEncountersIdRoute: typeof AuthDashboardEncountersIdRouteWithChildren
  AuthDashboardEncountersNewRoute: typeof AuthDashboardEncountersNewRoute
  AuthDashboardGrowthRegisterRoute: typeof AuthDashboardGrowthRegisterRoute
  AuthDashboardMedicalRecordsRecordIdRoute: typeof AuthDashboardMedicalRecordsRecordIdRouteWithChildren
  AuthDashboardMedicalRecordsNewRoute: typeof AuthDashboardMedicalRecordsNewRoute
  AuthDashboardPatientsPatientIdRoute: typeof AuthDashboardPatientsPatientIdRouteWithChildren
  AuthDashboardPatientsNewRoute: typeof AuthDashboardPatientsNewRoute
  AuthDashboardServicesServiceIdRoute: typeof AuthDashboardServicesServiceIdRouteWithChildren
  AuthDashboardServicesNewRoute: typeof AuthDashboardServicesNewRoute
  AuthDashboardAppointmentsIndexRoute: typeof AuthDashboardAppointmentsIndexRoute
  AuthDashboardDoctorsIndexRoute: typeof AuthDashboardDoctorsIndexRoute
  AuthDashboardEncountersIndexRoute: typeof AuthDashboardEncountersIndexRoute
  AuthDashboardGrowthIndexRoute: typeof AuthDashboardGrowthIndexRoute
  AuthDashboardMedicalRecordsIndexRoute: typeof AuthDashboardMedicalRecordsIndexRoute
  AuthDashboardPatientsIndexRoute: typeof AuthDashboardPatientsIndexRoute
  AuthDashboardServicesIndexRoute: typeof AuthDashboardServicesIndexRoute
  AuthDashboardGrowthPatientIdAddMeasurementRoute: typeof AuthDashboardGrowthPatientIdAddMeasurementRoute
  AuthDashboardGrowthPatientIdChartRoute: typeof AuthDashboardGrowthPatientIdChartRoute
  AuthDashboardServicesCloneServiceIdRoute: typeof AuthDashboardServicesCloneServiceIdRoute
  AuthDashboardGrowthPatientIdIndexRoute: typeof AuthDashboardGrowthPatientIdIndexRoute
}

const AuthDashboardRouteChildren: AuthDashboardRouteChildren = {
  AuthDashboardActivityRoute: AuthDashboardActivityRoute,
  AuthDashboardAdminRoute: AuthDashboardAdminRoute,
  AuthDashboardAlertsRoute: AuthDashboardAlertsRoute,
  AuthDashboardChatRoute: AuthDashboardChatRoute,
  AuthDashboardKanabanRoute: AuthDashboardKanabanRoute,
  AuthDashboardNotificationsRoute: AuthDashboardNotificationsRoute,
  AuthDashboardProfileRoute: AuthDashboardProfileRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardAppointmentsIdRoute:
    AuthDashboardAppointmentsIdRouteWithChildren,
  AuthDashboardAppointmentsNewRoute: AuthDashboardAppointmentsNewRoute,
  AuthDashboardAppointmentsTodayRoute: AuthDashboardAppointmentsTodayRoute,
  AuthDashboardDoctorsDoctorIdRoute: AuthDashboardDoctorsDoctorIdRoute,
  AuthDashboardDoctorsNewRoute: AuthDashboardDoctorsNewRoute,
  AuthDashboardEncountersIdRoute: AuthDashboardEncountersIdRouteWithChildren,
  AuthDashboardEncountersNewRoute: AuthDashboardEncountersNewRoute,
  AuthDashboardGrowthRegisterRoute: AuthDashboardGrowthRegisterRoute,
  AuthDashboardMedicalRecordsRecordIdRoute:
    AuthDashboardMedicalRecordsRecordIdRouteWithChildren,
  AuthDashboardMedicalRecordsNewRoute: AuthDashboardMedicalRecordsNewRoute,
  AuthDashboardPatientsPatientIdRoute:
    AuthDashboardPatientsPatientIdRouteWithChildren,
  AuthDashboardPatientsNewRoute: AuthDashboardPatientsNewRoute,
  AuthDashboardServicesServiceIdRoute:
    AuthDashboardServicesServiceIdRouteWithChildren,
  AuthDashboardServicesNewRoute: AuthDashboardServicesNewRoute,
  AuthDashboardAppointmentsIndexRoute: AuthDashboardAppointmentsIndexRoute,
  AuthDashboardDoctorsIndexRoute: AuthDashboardDoctorsIndexRoute,
  AuthDashboardEncountersIndexRoute: AuthDashboardEncountersIndexRoute,
  AuthDashboardGrowthIndexRoute: AuthDashboardGrowthIndexRoute,
  AuthDashboardMedicalRecordsIndexRoute: AuthDashboardMedicalRecordsIndexRoute,
  AuthDashboardPatientsIndexRoute: AuthDashboardPatientsIndexRoute,
  AuthDashboardServicesIndexRoute: AuthDashboardServicesIndexRoute,
  AuthDashboardGrowthPatientIdAddMeasurementRoute:
    AuthDashboardGrowthPatientIdAddMeasurementRoute,
  AuthDashboardGrowthPatientIdChartRoute:
    AuthDashboardGrowthPatientIdChartRoute,
  AuthDashboardServicesCloneServiceIdRoute:
    AuthDashboardServicesCloneServiceIdRoute,
  AuthDashboardGrowthPatientIdIndexRoute:
    AuthDashboardGrowthPatientIdIndexRoute,
}

const AuthDashboardRouteWithChildren = AuthDashboardRoute._addFileChildren(
  AuthDashboardRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthPathRoute: typeof AuthPathRoute
  AuthDashboardRoute: typeof AuthDashboardRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthPathRoute: AuthPathRoute,
  AuthDashboardRoute: AuthDashboardRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  AccountPathRoute: AccountPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
